version: "3.7"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Qwerty12"
            ACCEPT_EULA: "Y"
    api:
        build: .\BookStore.Api\BookStore.Api\.
        ports:
            - "1001:1001"
        depends_on:
            - db
    web:
        build: .\BookStore.Web\BookStore.Web\.
        ports:
            - "80:1002"
        depends_on:
            - api