version: "3.7"
services:
    web:
        build: .\BookStore.Web\BookStore.Web\.
        ports:
            - "81:80"
        depends_on:
            - api
    api:
        build: .\BookStore\BookStore.Api\.
        ports:
            - "1001:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
            - "1434:1434"
        environment:
            SA_PASSWORD: "Qwerty12"
            ACCEPT_EULA: "Y"